# Generated by tools/generate_piano_preloads.gd. Do not edit by hand.
extends Node

class PianoSample:
	extends Resource
	@export var file := ""
	@export var note := ""
	@export var stream: AudioStream

const PLAYER_VL1_RR1_A_1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A-1.ogg")
const PLAYER_VL1_RR1_A0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A0.ogg")
const PLAYER_VL1_RR1_A1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A1.ogg")
const PLAYER_VL1_RR1_A2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A2.ogg")
const PLAYER_VL1_RR1_A3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A3.ogg")
const PLAYER_VL1_RR1_A4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A4.ogg")
const PLAYER_VL1_RR1_A5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A5.ogg")
const PLAYER_VL1_RR1_A6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_A6.ogg")
const PLAYER_VL1_RR1_B_1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B-1.ogg")
const PLAYER_VL1_RR1_B0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B0.ogg")
const PLAYER_VL1_RR1_B1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B1.ogg")
const PLAYER_VL1_RR1_B2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B2.ogg")
const PLAYER_VL1_RR1_B3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B3.ogg")
const PLAYER_VL1_RR1_B4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B4.ogg")
const PLAYER_VL1_RR1_B5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B5.ogg")
const PLAYER_VL1_RR1_B6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_B6.ogg")
const PLAYER_VL1_RR1_C_0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#0.ogg")
const PLAYER_VL1_RR1_C_1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#1.ogg")
const PLAYER_VL1_RR1_C_2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#2.ogg")
const PLAYER_VL1_RR1_C_3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#3.ogg")
const PLAYER_VL1_RR1_C_4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#4.ogg")
const PLAYER_VL1_RR1_C_5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#5.ogg")
const PLAYER_VL1_RR1_C_6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C#6.ogg")
const PLAYER_VL1_RR1_C7_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_C7.ogg")
const PLAYER_VL1_RR1_D_0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#0.ogg")
const PLAYER_VL1_RR1_D_1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#1.ogg")
const PLAYER_VL1_RR1_D_2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#2.ogg")
const PLAYER_VL1_RR1_D_3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#3.ogg")
const PLAYER_VL1_RR1_D_4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#4.ogg")
const PLAYER_VL1_RR1_D_5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#5.ogg")
const PLAYER_VL1_RR1_D_6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_D#6.ogg")
const PLAYER_VL1_RR1_F0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F0.ogg")
const PLAYER_VL1_RR1_F1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F1.ogg")
const PLAYER_VL1_RR1_F2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F2.ogg")
const PLAYER_VL1_RR1_F3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F3.ogg")
const PLAYER_VL1_RR1_F4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F4.ogg")
const PLAYER_VL1_RR1_F5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F5.ogg")
const PLAYER_VL1_RR1_F6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_F6.ogg")
const PLAYER_VL1_RR1_G0_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G0.ogg")
const PLAYER_VL1_RR1_G1_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G1.ogg")
const PLAYER_VL1_RR1_G2_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G2.ogg")
const PLAYER_VL1_RR1_G3_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G3.ogg")
const PLAYER_VL1_RR1_G4_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G4.ogg")
const PLAYER_VL1_RR1_G5_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G5.ogg")
const PLAYER_VL1_RR1_G6_OGG = preload("res://assets/audio/piano/Player_vl1_rr1_G6.ogg")
const PLAYER_VL2_RR1_A_1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A-1.ogg")
const PLAYER_VL2_RR1_A0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A0.ogg")
const PLAYER_VL2_RR1_A1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A1.ogg")
const PLAYER_VL2_RR1_A2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A2.ogg")
const PLAYER_VL2_RR1_A3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A3.ogg")
const PLAYER_VL2_RR1_A4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A4.ogg")
const PLAYER_VL2_RR1_A5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A5.ogg")
const PLAYER_VL2_RR1_A6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_A6.ogg")
const PLAYER_VL2_RR1_B_1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B-1.ogg")
const PLAYER_VL2_RR1_B0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B0.ogg")
const PLAYER_VL2_RR1_B1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B1.ogg")
const PLAYER_VL2_RR1_B2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B2.ogg")
const PLAYER_VL2_RR1_B3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B3.ogg")
const PLAYER_VL2_RR1_B4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B4.ogg")
const PLAYER_VL2_RR1_B5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B5.ogg")
const PLAYER_VL2_RR1_B6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_B6.ogg")
const PLAYER_VL2_RR1_C_0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#0.ogg")
const PLAYER_VL2_RR1_C_1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#1.ogg")
const PLAYER_VL2_RR1_C_2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#2.ogg")
const PLAYER_VL2_RR1_C_3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#3.ogg")
const PLAYER_VL2_RR1_C_4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#4.ogg")
const PLAYER_VL2_RR1_C_5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#5.ogg")
const PLAYER_VL2_RR1_C_6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C#6.ogg")
const PLAYER_VL2_RR1_C7_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_C7.ogg")
const PLAYER_VL2_RR1_D_0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#0.ogg")
const PLAYER_VL2_RR1_D_1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#1.ogg")
const PLAYER_VL2_RR1_D_2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#2.ogg")
const PLAYER_VL2_RR1_D_3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#3.ogg")
const PLAYER_VL2_RR1_D_4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#4.ogg")
const PLAYER_VL2_RR1_D_5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#5.ogg")
const PLAYER_VL2_RR1_D_6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_D#6.ogg")
const PLAYER_VL2_RR1_F0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F0.ogg")
const PLAYER_VL2_RR1_F1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F1.ogg")
const PLAYER_VL2_RR1_F2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F2.ogg")
const PLAYER_VL2_RR1_F3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F3.ogg")
const PLAYER_VL2_RR1_F4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F4.ogg")
const PLAYER_VL2_RR1_F5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F5.ogg")
const PLAYER_VL2_RR1_F6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_F6.ogg")
const PLAYER_VL2_RR1_G0_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G0.ogg")
const PLAYER_VL2_RR1_G1_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G1.ogg")
const PLAYER_VL2_RR1_G2_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G2.ogg")
const PLAYER_VL2_RR1_G3_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G3.ogg")
const PLAYER_VL2_RR1_G4_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G4.ogg")
const PLAYER_VL2_RR1_G5_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G5.ogg")
const PLAYER_VL2_RR1_G6_OGG = preload("res://assets/audio/piano/Player_vl2_rr1_G6.ogg")

static func _entry(file: String, note: String, stream: AudioStream) -> PianoSample:
	var e := PianoSample.new()
	e.file = file
	e.note = note
	e.stream = stream
	return e

static func _build_entries() -> Array[PianoSample]:
	return [
		_entry("Player_vl1_rr1_A-1.ogg", "A-1", PLAYER_VL1_RR1_A_1_OGG),
		_entry("Player_vl1_rr1_A0.ogg", "A0", PLAYER_VL1_RR1_A0_OGG),
		_entry("Player_vl1_rr1_A1.ogg", "A1", PLAYER_VL1_RR1_A1_OGG),
		_entry("Player_vl1_rr1_A2.ogg", "A2", PLAYER_VL1_RR1_A2_OGG),
		_entry("Player_vl1_rr1_A3.ogg", "A3", PLAYER_VL1_RR1_A3_OGG),
		_entry("Player_vl1_rr1_A4.ogg", "A4", PLAYER_VL1_RR1_A4_OGG),
		_entry("Player_vl1_rr1_A5.ogg", "A5", PLAYER_VL1_RR1_A5_OGG),
		_entry("Player_vl1_rr1_A6.ogg", "A6", PLAYER_VL1_RR1_A6_OGG),
		_entry("Player_vl1_rr1_B-1.ogg", "B-1", PLAYER_VL1_RR1_B_1_OGG),
		_entry("Player_vl1_rr1_B0.ogg", "B0", PLAYER_VL1_RR1_B0_OGG),
		_entry("Player_vl1_rr1_B1.ogg", "B1", PLAYER_VL1_RR1_B1_OGG),
		_entry("Player_vl1_rr1_B2.ogg", "B2", PLAYER_VL1_RR1_B2_OGG),
		_entry("Player_vl1_rr1_B3.ogg", "B3", PLAYER_VL1_RR1_B3_OGG),
		_entry("Player_vl1_rr1_B4.ogg", "B4", PLAYER_VL1_RR1_B4_OGG),
		_entry("Player_vl1_rr1_B5.ogg", "B5", PLAYER_VL1_RR1_B5_OGG),
		_entry("Player_vl1_rr1_B6.ogg", "B6", PLAYER_VL1_RR1_B6_OGG),
		_entry("Player_vl1_rr1_C#0.ogg", "C#0", PLAYER_VL1_RR1_C_0_OGG),
		_entry("Player_vl1_rr1_C#1.ogg", "C#1", PLAYER_VL1_RR1_C_1_OGG),
		_entry("Player_vl1_rr1_C#2.ogg", "C#2", PLAYER_VL1_RR1_C_2_OGG),
		_entry("Player_vl1_rr1_C#3.ogg", "C#3", PLAYER_VL1_RR1_C_3_OGG),
		_entry("Player_vl1_rr1_C#4.ogg", "C#4", PLAYER_VL1_RR1_C_4_OGG),
		_entry("Player_vl1_rr1_C#5.ogg", "C#5", PLAYER_VL1_RR1_C_5_OGG),
		_entry("Player_vl1_rr1_C#6.ogg", "C#6", PLAYER_VL1_RR1_C_6_OGG),
		_entry("Player_vl1_rr1_C7.ogg", "C7", PLAYER_VL1_RR1_C7_OGG),
		_entry("Player_vl1_rr1_D#0.ogg", "D#0", PLAYER_VL1_RR1_D_0_OGG),
		_entry("Player_vl1_rr1_D#1.ogg", "D#1", PLAYER_VL1_RR1_D_1_OGG),
		_entry("Player_vl1_rr1_D#2.ogg", "D#2", PLAYER_VL1_RR1_D_2_OGG),
		_entry("Player_vl1_rr1_D#3.ogg", "D#3", PLAYER_VL1_RR1_D_3_OGG),
		_entry("Player_vl1_rr1_D#4.ogg", "D#4", PLAYER_VL1_RR1_D_4_OGG),
		_entry("Player_vl1_rr1_D#5.ogg", "D#5", PLAYER_VL1_RR1_D_5_OGG),
		_entry("Player_vl1_rr1_D#6.ogg", "D#6", PLAYER_VL1_RR1_D_6_OGG),
		_entry("Player_vl1_rr1_F0.ogg", "F0", PLAYER_VL1_RR1_F0_OGG),
		_entry("Player_vl1_rr1_F1.ogg", "F1", PLAYER_VL1_RR1_F1_OGG),
		_entry("Player_vl1_rr1_F2.ogg", "F2", PLAYER_VL1_RR1_F2_OGG),
		_entry("Player_vl1_rr1_F3.ogg", "F3", PLAYER_VL1_RR1_F3_OGG),
		_entry("Player_vl1_rr1_F4.ogg", "F4", PLAYER_VL1_RR1_F4_OGG),
		_entry("Player_vl1_rr1_F5.ogg", "F5", PLAYER_VL1_RR1_F5_OGG),
		_entry("Player_vl1_rr1_F6.ogg", "F6", PLAYER_VL1_RR1_F6_OGG),
		_entry("Player_vl1_rr1_G0.ogg", "G0", PLAYER_VL1_RR1_G0_OGG),
		_entry("Player_vl1_rr1_G1.ogg", "G1", PLAYER_VL1_RR1_G1_OGG),
		_entry("Player_vl1_rr1_G2.ogg", "G2", PLAYER_VL1_RR1_G2_OGG),
		_entry("Player_vl1_rr1_G3.ogg", "G3", PLAYER_VL1_RR1_G3_OGG),
		_entry("Player_vl1_rr1_G4.ogg", "G4", PLAYER_VL1_RR1_G4_OGG),
		_entry("Player_vl1_rr1_G5.ogg", "G5", PLAYER_VL1_RR1_G5_OGG),
		_entry("Player_vl1_rr1_G6.ogg", "G6", PLAYER_VL1_RR1_G6_OGG),
		_entry("Player_vl2_rr1_A-1.ogg", "A-1", PLAYER_VL2_RR1_A_1_OGG),
		_entry("Player_vl2_rr1_A0.ogg", "A0", PLAYER_VL2_RR1_A0_OGG),
		_entry("Player_vl2_rr1_A1.ogg", "A1", PLAYER_VL2_RR1_A1_OGG),
		_entry("Player_vl2_rr1_A2.ogg", "A2", PLAYER_VL2_RR1_A2_OGG),
		_entry("Player_vl2_rr1_A3.ogg", "A3", PLAYER_VL2_RR1_A3_OGG),
		_entry("Player_vl2_rr1_A4.ogg", "A4", PLAYER_VL2_RR1_A4_OGG),
		_entry("Player_vl2_rr1_A5.ogg", "A5", PLAYER_VL2_RR1_A5_OGG),
		_entry("Player_vl2_rr1_A6.ogg", "A6", PLAYER_VL2_RR1_A6_OGG),
		_entry("Player_vl2_rr1_B-1.ogg", "B-1", PLAYER_VL2_RR1_B_1_OGG),
		_entry("Player_vl2_rr1_B0.ogg", "B0", PLAYER_VL2_RR1_B0_OGG),
		_entry("Player_vl2_rr1_B1.ogg", "B1", PLAYER_VL2_RR1_B1_OGG),
		_entry("Player_vl2_rr1_B2.ogg", "B2", PLAYER_VL2_RR1_B2_OGG),
		_entry("Player_vl2_rr1_B3.ogg", "B3", PLAYER_VL2_RR1_B3_OGG),
		_entry("Player_vl2_rr1_B4.ogg", "B4", PLAYER_VL2_RR1_B4_OGG),
		_entry("Player_vl2_rr1_B5.ogg", "B5", PLAYER_VL2_RR1_B5_OGG),
		_entry("Player_vl2_rr1_B6.ogg", "B6", PLAYER_VL2_RR1_B6_OGG),
		_entry("Player_vl2_rr1_C#0.ogg", "C#0", PLAYER_VL2_RR1_C_0_OGG),
		_entry("Player_vl2_rr1_C#1.ogg", "C#1", PLAYER_VL2_RR1_C_1_OGG),
		_entry("Player_vl2_rr1_C#2.ogg", "C#2", PLAYER_VL2_RR1_C_2_OGG),
		_entry("Player_vl2_rr1_C#3.ogg", "C#3", PLAYER_VL2_RR1_C_3_OGG),
		_entry("Player_vl2_rr1_C#4.ogg", "C#4", PLAYER_VL2_RR1_C_4_OGG),
		_entry("Player_vl2_rr1_C#5.ogg", "C#5", PLAYER_VL2_RR1_C_5_OGG),
		_entry("Player_vl2_rr1_C#6.ogg", "C#6", PLAYER_VL2_RR1_C_6_OGG),
		_entry("Player_vl2_rr1_C7.ogg", "C7", PLAYER_VL2_RR1_C7_OGG),
		_entry("Player_vl2_rr1_D#0.ogg", "D#0", PLAYER_VL2_RR1_D_0_OGG),
		_entry("Player_vl2_rr1_D#1.ogg", "D#1", PLAYER_VL2_RR1_D_1_OGG),
		_entry("Player_vl2_rr1_D#2.ogg", "D#2", PLAYER_VL2_RR1_D_2_OGG),
		_entry("Player_vl2_rr1_D#3.ogg", "D#3", PLAYER_VL2_RR1_D_3_OGG),
		_entry("Player_vl2_rr1_D#4.ogg", "D#4", PLAYER_VL2_RR1_D_4_OGG),
		_entry("Player_vl2_rr1_D#5.ogg", "D#5", PLAYER_VL2_RR1_D_5_OGG),
		_entry("Player_vl2_rr1_D#6.ogg", "D#6", PLAYER_VL2_RR1_D_6_OGG),
		_entry("Player_vl2_rr1_F0.ogg", "F0", PLAYER_VL2_RR1_F0_OGG),
		_entry("Player_vl2_rr1_F1.ogg", "F1", PLAYER_VL2_RR1_F1_OGG),
		_entry("Player_vl2_rr1_F2.ogg", "F2", PLAYER_VL2_RR1_F2_OGG),
		_entry("Player_vl2_rr1_F3.ogg", "F3", PLAYER_VL2_RR1_F3_OGG),
		_entry("Player_vl2_rr1_F4.ogg", "F4", PLAYER_VL2_RR1_F4_OGG),
		_entry("Player_vl2_rr1_F5.ogg", "F5", PLAYER_VL2_RR1_F5_OGG),
		_entry("Player_vl2_rr1_F6.ogg", "F6", PLAYER_VL2_RR1_F6_OGG),
		_entry("Player_vl2_rr1_G0.ogg", "G0", PLAYER_VL2_RR1_G0_OGG),
		_entry("Player_vl2_rr1_G1.ogg", "G1", PLAYER_VL2_RR1_G1_OGG),
		_entry("Player_vl2_rr1_G2.ogg", "G2", PLAYER_VL2_RR1_G2_OGG),
		_entry("Player_vl2_rr1_G3.ogg", "G3", PLAYER_VL2_RR1_G3_OGG),
		_entry("Player_vl2_rr1_G4.ogg", "G4", PLAYER_VL2_RR1_G4_OGG),
		_entry("Player_vl2_rr1_G5.ogg", "G5", PLAYER_VL2_RR1_G5_OGG),
		_entry("Player_vl2_rr1_G6.ogg", "G6", PLAYER_VL2_RR1_G6_OGG),
	]

static var ENTRIES: Array[PianoSample] = _build_entries()
