#!/usr/bin/env python3
"""Helpers for the Android release build, driven by Taskfile.yml.

Kept in Python rather than sed/grep so the same commands work in a plain
Windows shell and on the Linux CI runner.
"""

import argparse
import io
import os
import re
import sys

CONFIG_GRADLE = os.path.join("android", "build", "config.gradle")
EXPORT_PRESETS = "export_presets.cfg"
MERGED_MANIFEST = os.path.join(
    "android", "build", "build", "intermediates", "merged_manifest",
    "standardRelease", "processStandardReleaseMainManifest", "AndroidManifest.xml",
)


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def write(path, text):
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def patch_template(args):
    """Re-apply the SDK bump to Godot's generated Android build template.

    android/ is gitignored and regenerated by --install-android-build-template,
    so this has to run after every template (re)install.
    """
    if not os.path.isfile(CONFIG_GRADLE):
        sys.exit(
            "%s not found - run 'task android-template' first." % CONFIG_GRADLE
        )

    text = read(CONFIG_GRADLE)
    edits = [
        (r"(\n\s*compileSdk\s*:\s*)\d+,", r"\g<1>%s," % args.compile_sdk),
        (r"(\n\s*targetSdk\s*:\s*)\d+,", r"\g<1>%s," % args.target_sdk),
        (r"(\n\s*buildTools\s*:\s*')[^']+',", r"\g<1>%s'," % args.build_tools),
    ]
    for pattern, replacement in edits:
        text, count = re.subn(pattern, replacement, text, count=1)
        if not count:
            sys.exit("Could not apply %r - did the template layout change?" % pattern)

    write(CONFIG_GRADLE, text)
    for line in read(CONFIG_GRADLE).splitlines():
        if re.search(r"(compileSdk|targetSdk|buildTools)\s*:", line):
            print(line.strip())


def verify(args):
    """Assert the manifest the build actually produced targets the right SDK."""
    if not os.path.isfile(MERGED_MANIFEST):
        sys.exit("No merged manifest at %s - build the .aab first." % MERGED_MANIFEST)

    manifest = read(MERGED_MANIFEST)
    found = {}
    for key in ("targetSdkVersion", "minSdkVersion", "versionCode", "versionName"):
        match = re.search(r'%s="([^"]*)"' % key, manifest)
        found[key] = match.group(1) if match else "?"
        print("%s=%s" % (key, found[key]))

    if found["targetSdkVersion"] != args.target_sdk:
        sys.exit(
            "FAIL: built manifest targets SDK %s, expected %s"
            % (found["targetSdkVersion"], args.target_sdk)
        )
    print("OK: targets Android SDK %s" % args.target_sdk)


def bump(args):
    """Increment version/code so Play accepts the upload."""
    text = read(EXPORT_PRESETS)
    match = re.search(r"(?m)^version/code=(\d+)$", text)
    if not match:
        sys.exit("No 'version/code=' line in %s" % EXPORT_PRESETS)

    current = int(match.group(1))
    following = current + 1
    text = "%s%d%s" % (text[: match.start(1)], following, text[match.end(1) :])
    write(EXPORT_PRESETS, text)
    print("version/code: %d -> %d" % (current, following))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command")
    sub.required = True

    p = sub.add_parser("patch-template", help="bump SDK versions in config.gradle")
    p.add_argument("--compile-sdk", required=True)
    p.add_argument("--target-sdk", required=True)
    p.add_argument("--build-tools", required=True)
    p.set_defaults(func=patch_template)

    p = sub.add_parser("verify", help="check the built manifest's targetSdkVersion")
    p.add_argument("--target-sdk", required=True)
    p.set_defaults(func=verify)

    p = sub.add_parser("bump", help="increment the Android version/code")
    p.set_defaults(func=bump)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
