#!/usr/bin/env python3
"""Helpers for the Android release build, driven by Taskfile.yml.

Kept in Python rather than sed/grep so the same commands work in a plain
Windows shell and on the Linux CI runner.
"""

import argparse
import io
import os
import re
import shutil
import stat
import sys
import zipfile

ANDROID_DIR = "android"
BUILD_DIR = os.path.join("android", "build")
CONFIG_GRADLE = os.path.join("android", "build", "config.gradle")
EXPORT_PRESETS = "export_presets.cfg"
MERGED_MANIFEST = os.path.join(
    "android", "build", "build", "intermediates", "merged_manifest",
    "standardRelease", "processStandardReleaseMainManifest", "AndroidManifest.xml",
)


def read(path):
    with io.open(path, encoding="utf-8") as handle:
        return handle.read()


def write(path, text):
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def templates_root():
    """Where the Godot editor keeps its downloaded export templates."""
    override = os.environ.get("GODOT_EXPORT_TEMPLATES")
    if override:
        return override
    if sys.platform == "win32":
        return os.path.join(os.environ["APPDATA"], "Godot", "export_templates")
    if sys.platform == "darwin":
        return os.path.expanduser(
            "~/Library/Application Support/Godot/export_templates"
        )
    return os.path.expanduser("~/.local/share/godot/export_templates")


def resolve_version_dir(root, requested):
    if requested:
        path = os.path.join(root, requested)
        if not os.path.isdir(path):
            sys.exit("No export templates for %s in %s" % (requested, root))
        return requested, path

    if not os.path.isdir(root):
        sys.exit(
            "No export templates found in %s. Install them from the Godot editor "
            "(Editor -> Manage Export Templates)." % root
        )
    installed = sorted(
        name for name in os.listdir(root) if os.path.isdir(os.path.join(root, name))
    )
    if len(installed) != 1:
        sys.exit(
            "Found %d template versions in %s (%s). Pass --godot-version to pick one."
            % (len(installed), root, ", ".join(installed) or "none")
        )
    return installed[0], os.path.join(root, installed[0])


def install_template(args):
    """Unpack Godot's Android build template into android/build.

    This is what the editor's "Install Android Build Template" menu item does.
    Godot's --install-android-build-template flag is not used because it only
    works alongside an --export-* flag; on its own it starts the editor and
    never exits, which hangs a CI runner.
    """
    root = templates_root()
    version, version_dir = resolve_version_dir(root, args.godot_version)
    source_zip = os.path.join(version_dir, "android_source.zip")
    if not os.path.isfile(source_zip):
        sys.exit("No android_source.zip in %s" % version_dir)

    if os.path.isdir(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
    os.makedirs(BUILD_DIR)

    with zipfile.ZipFile(source_zip) as archive:
        archive.extractall(BUILD_DIR)
        # extractall drops the executable bit, which Linux needs for gradlew.
        for entry in archive.infolist():
            mode = entry.external_attr >> 16
            if mode and not entry.is_dir():
                target = os.path.join(BUILD_DIR, entry.filename)
                if os.path.exists(target):
                    os.chmod(target, stat.S_IMODE(mode))

    # Markers the editor writes so it treats the template as installed.
    write(os.path.join(ANDROID_DIR, ".build_version"), version + "\n")
    open(os.path.join(BUILD_DIR, ".gdignore"), "w").close()

    print("Installed Android build template %s from %s" % (version, source_zip))


def patch_template(args):
    """Re-apply the SDK bump to Godot's generated Android build template.

    android/ is gitignored and regenerated by --install-android-build-template,
    so this has to run after every template (re)install.
    """
    if not os.path.isfile(CONFIG_GRADLE):
        sys.exit(
            "%s not found - run 'task android-template' first." % CONFIG_GRADLE
        )

    text = read(CONFIG_GRADLE)
    edits = [
        (r"(\n\s*compileSdk\s*:\s*)\d+,", r"\g<1>%s," % args.compile_sdk),
        (r"(\n\s*targetSdk\s*:\s*)\d+,", r"\g<1>%s," % args.target_sdk),
        (r"(\n\s*buildTools\s*:\s*')[^']+',", r"\g<1>%s'," % args.build_tools),
    ]
    for pattern, replacement in edits:
        text, count = re.subn(pattern, replacement, text, count=1)
        if not count:
            sys.exit("Could not apply %r - did the template layout change?" % pattern)

    write(CONFIG_GRADLE, text)
    for line in read(CONFIG_GRADLE).splitlines():
        if re.search(r"(compileSdk|targetSdk|buildTools)\s*:", line):
            print(line.strip())


def verify(args):
    """Assert the manifest the build actually produced targets the right SDK."""
    if not os.path.isfile(MERGED_MANIFEST):
        sys.exit("No merged manifest at %s - build the .aab first." % MERGED_MANIFEST)

    manifest = read(MERGED_MANIFEST)
    found = {}
    for key in ("targetSdkVersion", "minSdkVersion", "versionCode", "versionName"):
        match = re.search(r'%s="([^"]*)"' % key, manifest)
        found[key] = match.group(1) if match else "?"
        print("%s=%s" % (key, found[key]))

    if found["targetSdkVersion"] != args.target_sdk:
        sys.exit(
            "FAIL: built manifest targets SDK %s, expected %s"
            % (found["targetSdkVersion"], args.target_sdk)
        )
    print("OK: targets Android SDK %s" % args.target_sdk)


def bump(args):
    """Increment version/code so Play accepts the upload."""
    text = read(EXPORT_PRESETS)
    match = re.search(r"(?m)^version/code=(\d+)$", text)
    if not match:
        sys.exit("No 'version/code=' line in %s" % EXPORT_PRESETS)

    current = int(match.group(1))
    following = current + 1
    text = "%s%d%s" % (text[: match.start(1)], following, text[match.end(1) :])
    write(EXPORT_PRESETS, text)
    print("version/code: %d -> %d" % (current, following))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command")
    sub.required = True

    p = sub.add_parser("install-template", help="unpack the Android build template")
    p.add_argument(
        "--godot-version",
        help='template version directory, e.g. "4.5.1.stable" '
        "(default: the only one installed)",
    )
    p.set_defaults(func=install_template)

    p = sub.add_parser("patch-template", help="bump SDK versions in config.gradle")
    p.add_argument("--compile-sdk", required=True)
    p.add_argument("--target-sdk", required=True)
    p.add_argument("--build-tools", required=True)
    p.set_defaults(func=patch_template)

    p = sub.add_parser("verify", help="check the built manifest's targetSdkVersion")
    p.add_argument("--target-sdk", required=True)
    p.set_defaults(func=verify)

    p = sub.add_parser("bump", help="increment the Android version/code")
    p.set_defaults(func=bump)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
