@tool
extends EditorScript

const SOURCE_DIR := "res://assets/audio/piano"
const OUTPUT_PATH := "res://game/piano_samples.gd"
const NOTE_EXTENSION := ".ogg"

func _const_name_for(file_name: String) -> String:
	var name := file_name.to_upper()
	var out := ""
	for i in name.length():
		var code := name.unicode_at(i)
		var is_alpha := code >= 65 and code <= 90
		var is_digit := code >= 48 and code <= 57
		if is_alpha or is_digit:
			out += name[i]
		else:
			out += "_"
	while out.find("__") != -1:
		out = out.replace("__", "_")
	out = out.strip_edges()
	out = out.trim_prefix("_")
	out = out.trim_suffix("_")
	if out == "" or (out[0].unicode_at(0) >= 48 and out[0].unicode_at(0) <= 57):
		out = "FILE_" + out
	return out

func _note_from_filename(file_name: String) -> String:
	var regex := RegEx.new()
	regex.compile("_([A-G](?:#|b)?-?\\d+)\\" + NOTE_EXTENSION + "$")
	var result := regex.search(file_name)
	if result == null:
		return ""
	return result.get_string(1)

func _run() -> void:
	var dir := DirAccess.open(SOURCE_DIR)
	if dir == null:
		push_error("Missing piano samples directory: %s" % [SOURCE_DIR])
		return

	var files: Array[String] = []
	dir.list_dir_begin()
	var file_name := dir.get_next()
	while file_name != "":
		if not dir.current_is_dir() and file_name.to_lower().ends_with(NOTE_EXTENSION):
			files.append(file_name)
		file_name = dir.get_next()
	dir.list_dir_end()

	files.sort()

	var f := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if f == null:
		push_error("Failed to open output file: %s" % [OUTPUT_PATH])
		return

	f.store_line("# Generated by tools/generate_piano_preloads.gd. Do not edit by hand.")
	f.store_line("extends Node")
	f.store_line("")
	f.store_line("class PianoSample:")
	f.store_line("\textends Resource")
	f.store_line("\t@export var file := \"\"")
	f.store_line("\t@export var note := \"\"")
	f.store_line("\t@export var stream: AudioStream")
	f.store_line("")
	for i in range(files.size()):
		var name := files[i]
		var const_name := _const_name_for(name)
		var path := "%s/%s" % [SOURCE_DIR, name]
		var line := "const %s = preload(\"%s\")" % [const_name, path]
		f.store_line(line)
	f.store_line("")
	f.store_line("static func _entry(file: String, note: String, stream: AudioStream) -> PianoSample:")
	f.store_line("\tvar e := PianoSample.new()")
	f.store_line("\te.file = file")
	f.store_line("\te.note = note")
	f.store_line("\te.stream = stream")
	f.store_line("\treturn e")
	f.store_line("")
	f.store_line("static func _build_entries() -> Array[PianoSample]:")
	f.store_line("\treturn [")
	for i in range(files.size()):
		var name := files[i]
		var const_name := _const_name_for(name)
		var note := _note_from_filename(name)
		var line := "\t\t_entry(\"%s\", \"%s\", %s)," % [name, note, const_name]
		f.store_line(line)
	f.store_line("\t]")
	f.store_line("")
	f.store_line("static var ENTRIES: Array[PianoSample] = _build_entries()")
	f.close()

	print("Wrote %d samples to %s" % [files.size(), OUTPUT_PATH])
